from tkinter import*
root=Tk()
root.title("Demo Application")
root.geometry("500x300+500+300")
root.config(bg="red")
lb1=Label(text="Welcome to Tkinter")
lb1.pack(pady=20)
lb2=Label(text="python class")
lb2.pack()
mainloop()